version: "3.3"
services:
  nlweststandings:
    stdin_open: true
    tty: true
    ports:
      - 8089:8080
      - 8090:8081
    image: nlweststandings
networks:
  dockge_default:
    external: true
